# Generated by Django 3.2.9 on 2021-11-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
